Downloading an annotation was causing an error
cmd: $genomepy install GRCz11 ncbi -a
error: invalid unsigned integer: "+"
which was caused by genePredToBed after recieving the output from gff3ToGenePred.

Previous method: convert GFF to BED, then convert BED to GTF.
Solution: convert GFF to GTF, then convert GTF to BED.